### ISSUE TITLE
Permissive license possible?

### ISSUE THREAD

**Issue by LPeteR90** [jld3103/dart-nextcloud#54]
Hi @jld3103, I would like to use this library in a commercially used closed-source Flutter app for mobile platforms as an interface to NextCloud. But since it is licensed under the GPLv3 it is (at least based on my understanding) not possible for me to use it in an app that is released to the Google Play Store or the Apple App Store. Would it be possible for you to change the license to a more permissive one like MIT or BSD or provide the library with a dual license?

Thanks for your help and also for your work so far on this great project.

Kind regards

**Comment by provokateurin** [comment]
I'm fine with licensing it under BSD like. @fingeg any thoughts?

**Comment by greyhairredbear** [comment]
Thank you, that sounds great :) Is there an approximate schedule on when you would be able to do that or do you first need to talk this through with @fingeg ?

**Comment by greyhairredbear** [comment]
Hi, happy holidays!

Since it's been a few days since I posted the question, I wanted to ask whether there's any update on this subject. @fingeg @jld3103

**Comment by provokateurin** [comment]
I think I can just replace the license. I'll do it this evening, but if not please remind me tomorrow. Btw what app are you working on? I think it might be cool to make a list of apps that use this library (@vauvenal5 you could add your app too).

**Comment by provokateurin** [comment]
I published it as `3.0.2`

**Comment by greyhairredbear** [comment]
@jld3103 That's great news, thank you a lot. Just a note regarding the license: There is still a placeholder in the liability clause (```IN NO EVENT SHALL `<COPYRIGHT HOLDER>` BE LIABLE FOR ANY...```), don't know if that's intended. 

I don't know how many details I can share about the app and would like to get some information on that from my company (and since everybody is on holiday until the new year it will at least take until then to get that information), but basically it is intended to be used as some kind of postbox for business documents for clients of our client company.

**Comment by provokateurin** [comment]
Oh yes I missed that...

As far as I understood you, you will publish the app on the app stores, right? Just dropping a link into the readme would be great, so people can see that is library is used by actual apps :)
